services:
  frontend:
    build: ./frontend/Dockerfile
    command: npm install && npm run build --port 5173
    ports:
      - "5173:5173"
    restart: always
    environment:
      - VITE_API_URL=http://backend:8000/api
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://db:5432/postgres
      - REDIS_URL=redis://redis:6379